[[ZlibNG]]
arch = "aarch64"
git-tree-sha1 = "8d231329cf529499cd7760610056f3e8ac387904"
os = "macos"

    [[ZlibNG.download]]
    sha256 = "760a248d279a54fd69b93c2f62825ea50e744525c2c4c097660a2b1137538b2a"
    url = "https://github.com/JuliaBinaryWrappers/ZlibNG_jll.jl/releases/download/ZlibNG-v2.1.6+0/ZlibNG.v2.1.6.aarch64-apple-darwin.tar.gz"
[[ZlibNG]]
arch = "aarch64"
git-tree-sha1 = "5a7d20dffab2786e5698aee4a6930df6a35544cc"
libc = "glibc"
os = "linux"

    [[ZlibNG.download]]
    sha256 = "e96727ea3924c505f1eec3391d9b2cc27e1ecdaf95a462c51a619cfd982bad03"
    url = "https://github.com/JuliaBinaryWrappers/ZlibNG_jll.jl/releases/download/ZlibNG-v2.1.6+0/ZlibNG.v2.1.6.aarch64-linux-gnu.tar.gz"
[[ZlibNG]]
arch = "aarch64"
git-tree-sha1 = "549b53139c485fb3ea9e0ff3b06ab6ed041074e4"
libc = "musl"
os = "linux"

    [[ZlibNG.download]]
    sha256 = "c0ae7b23a1cc88bf572a8a066c712ac2dd018a9140112389cbf2fd9f4cffacec"
    url = "https://github.com/JuliaBinaryWrappers/ZlibNG_jll.jl/releases/download/ZlibNG-v2.1.6+0/ZlibNG.v2.1.6.aarch64-linux-musl.tar.gz"
[[ZlibNG]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "e6872542cad390ed4f99dff2a06d5af6426ca46b"
libc = "glibc"
os = "linux"

    [[ZlibNG.download]]
    sha256 = "4a6b8c80a7e1c6d83be45ff42a6bed4b458c3a896b55c219dfa7f8964be92b62"
    url = "https://github.com/JuliaBinaryWrappers/ZlibNG_jll.jl/releases/download/ZlibNG-v2.1.6+0/ZlibNG.v2.1.6.armv6l-linux-gnueabihf.tar.gz"
[[ZlibNG]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "4e9a9a2778b9b84dc86c0103421719277f6f19ac"
libc = "musl"
os = "linux"

    [[ZlibNG.download]]
    sha256 = "62ef6c8d28e5e3d132dd96140f0f53df2246c4006a70464724fc6eb6438ebd72"
    url = "https://github.com/JuliaBinaryWrappers/ZlibNG_jll.jl/releases/download/ZlibNG-v2.1.6+0/ZlibNG.v2.1.6.armv6l-linux-musleabihf.tar.gz"
[[ZlibNG]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "f2db0a7c954b2bd6d3e9ccb7a88cb5875f9df7a3"
libc = "glibc"
os = "linux"

    [[ZlibNG.download]]
    sha256 = "d74ca7cda0b240e7b571a112cc63e53b9d684420f6c0f1c2569353ea1556748d"
    url = "https://github.com/JuliaBinaryWrappers/ZlibNG_jll.jl/releases/download/ZlibNG-v2.1.6+0/ZlibNG.v2.1.6.armv7l-linux-gnueabihf.tar.gz"
[[ZlibNG]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "5875f2a19f45667b2c2308d265bcb09f537d09d0"
libc = "musl"
os = "linux"

    [[ZlibNG.download]]
    sha256 = "4aa27073dd7f78bc0dd62742d679ac355bfdfea089f30479ed2a29a740a23a2b"
    url = "https://github.com/JuliaBinaryWrappers/ZlibNG_jll.jl/releases/download/ZlibNG-v2.1.6+0/ZlibNG.v2.1.6.armv7l-linux-musleabihf.tar.gz"
[[ZlibNG]]
arch = "i686"
git-tree-sha1 = "61f421dfea1f11e264fdd427e3e3a8fa581ed95e"
libc = "glibc"
os = "linux"

    [[ZlibNG.download]]
    sha256 = "ae7e11a5e1b101ded31e4f7a68c5b3eb26acda23919e3ed40172672994fb2896"
    url = "https://github.com/JuliaBinaryWrappers/ZlibNG_jll.jl/releases/download/ZlibNG-v2.1.6+0/ZlibNG.v2.1.6.i686-linux-gnu.tar.gz"
[[ZlibNG]]
arch = "i686"
git-tree-sha1 = "8df71054818cf9158a4684045e09964856f22c22"
libc = "musl"
os = "linux"

    [[ZlibNG.download]]
    sha256 = "c081f98b027d2bd542e5092ccb98e3d99b6b2c9c3ad312c05e997b24095128c1"
    url = "https://github.com/JuliaBinaryWrappers/ZlibNG_jll.jl/releases/download/ZlibNG-v2.1.6+0/ZlibNG.v2.1.6.i686-linux-musl.tar.gz"
[[ZlibNG]]
arch = "i686"
git-tree-sha1 = "ab4641186d1607d3454ab0d9e8f3d0a8891bb6b7"
os = "windows"

    [[ZlibNG.download]]
    sha256 = "a21429a123fbdaa05c70d74458735c7d335621ff4eef32ab84bdb45282cc142f"
    url = "https://github.com/JuliaBinaryWrappers/ZlibNG_jll.jl/releases/download/ZlibNG-v2.1.6+0/ZlibNG.v2.1.6.i686-w64-mingw32.tar.gz"
[[ZlibNG]]
arch = "powerpc64le"
git-tree-sha1 = "4b6cea66f2285969044d851c03c622e1ecbd2cc5"
libc = "glibc"
os = "linux"

    [[ZlibNG.download]]
    sha256 = "a3fca8295af001378807f8c2b9f714877b44f9ff817e974ba8cee3448df2d2ff"
    url = "https://github.com/JuliaBinaryWrappers/ZlibNG_jll.jl/releases/download/ZlibNG-v2.1.6+0/ZlibNG.v2.1.6.powerpc64le-linux-gnu.tar.gz"
[[ZlibNG]]
arch = "x86_64"
git-tree-sha1 = "d55f07023a8389565dfe2282064b7f4963c372c7"
os = "macos"

    [[ZlibNG.download]]
    sha256 = "90a37883a1cf6bc6ec01c9b5fd467bfc5fd952abfa15c112951af4e5545ca41e"
    url = "https://github.com/JuliaBinaryWrappers/ZlibNG_jll.jl/releases/download/ZlibNG-v2.1.6+0/ZlibNG.v2.1.6.x86_64-apple-darwin.tar.gz"
[[ZlibNG]]
arch = "x86_64"
git-tree-sha1 = "d743edc711270dfca005349fc5904fbc51a84b72"
libc = "glibc"
os = "linux"

    [[ZlibNG.download]]
    sha256 = "4b98f178d48397c38c181e88a1756ca972054f092893410e11d8ab43a87ff0ac"
    url = "https://github.com/JuliaBinaryWrappers/ZlibNG_jll.jl/releases/download/ZlibNG-v2.1.6+0/ZlibNG.v2.1.6.x86_64-linux-gnu.tar.gz"
[[ZlibNG]]
arch = "x86_64"
git-tree-sha1 = "6054737438ad303c95a1558f54c46fca132f0f49"
libc = "musl"
os = "linux"

    [[ZlibNG.download]]
    sha256 = "bb95b60ce25b954a024945d0a3b70a11b66ebeb6ede1b02732cc5469c10c9bc8"
    url = "https://github.com/JuliaBinaryWrappers/ZlibNG_jll.jl/releases/download/ZlibNG-v2.1.6+0/ZlibNG.v2.1.6.x86_64-linux-musl.tar.gz"
[[ZlibNG]]
arch = "x86_64"
git-tree-sha1 = "3d28ea0240c8b5c31120ac9493e27f9568d81cb7"
os = "freebsd"

    [[ZlibNG.download]]
    sha256 = "fe00066fcde3a383cb8dec2f751542e849790b51da78633fa9a9d0d8ed9ad833"
    url = "https://github.com/JuliaBinaryWrappers/ZlibNG_jll.jl/releases/download/ZlibNG-v2.1.6+0/ZlibNG.v2.1.6.x86_64-unknown-freebsd.tar.gz"
[[ZlibNG]]
arch = "x86_64"
git-tree-sha1 = "4333ab763e667fc2af80254cc1f19d237e86db02"
os = "windows"

    [[ZlibNG.download]]
    sha256 = "22f4f4d629a8d6ba5e8ee5cdac3fcfaa39d84ca7351f908dd83f961123aaa1df"
    url = "https://github.com/JuliaBinaryWrappers/ZlibNG_jll.jl/releases/download/ZlibNG-v2.1.6+0/ZlibNG.v2.1.6.x86_64-w64-mingw32.tar.gz"
