[[ZlibNG]]
arch = "aarch64"
git-tree-sha1 = "6c90592cdb11a83076bfd6979090a0f65a119485"
os = "macos"

    [[ZlibNG.download]]
    sha256 = "cc46031f785262a9bf3ab16b797b389637b7beccd45b2ae382c614102e0375eb"
    url = "https://github.com/JuliaBinaryWrappers/ZlibNG_jll.jl/releases/download/ZlibNG-v2.3.2+0/ZlibNG.v2.3.2.aarch64-apple-darwin.tar.gz"
[[ZlibNG]]
arch = "aarch64"
git-tree-sha1 = "7e6f2a616101250dcc024a2a92d1b7e7fcf2724c"
libc = "glibc"
os = "linux"

    [[ZlibNG.download]]
    sha256 = "2d7741ae52c049704290061a42b04b2b6c1e47e58feaca3fe7e7271643bbe857"
    url = "https://github.com/JuliaBinaryWrappers/ZlibNG_jll.jl/releases/download/ZlibNG-v2.3.2+0/ZlibNG.v2.3.2.aarch64-linux-gnu.tar.gz"
[[ZlibNG]]
arch = "aarch64"
git-tree-sha1 = "200e0fbeebaf16a512abf85b14b2581b8854abb9"
libc = "musl"
os = "linux"

    [[ZlibNG.download]]
    sha256 = "0e8c6ee15680414db2b1304946a597e4419794aa1baaa0d3ce89bd46e8dfbc63"
    url = "https://github.com/JuliaBinaryWrappers/ZlibNG_jll.jl/releases/download/ZlibNG-v2.3.2+0/ZlibNG.v2.3.2.aarch64-linux-musl.tar.gz"
[[ZlibNG]]
arch = "aarch64"
git-tree-sha1 = "335ebc1c2bea7bc4fd3cedd9266af66c286670b1"
os = "freebsd"

    [[ZlibNG.download]]
    sha256 = "047801b8c1c3f1315754697e192ee4b6dc7f7898cdda3ed1dc8af282f8763cf8"
    url = "https://github.com/JuliaBinaryWrappers/ZlibNG_jll.jl/releases/download/ZlibNG-v2.3.2+0/ZlibNG.v2.3.2.aarch64-unknown-freebsd.tar.gz"
[[ZlibNG]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "bd32f2452e95c4b3f39217511a8e7e13146cdb72"
libc = "glibc"
os = "linux"

    [[ZlibNG.download]]
    sha256 = "631d85ef3c570f39f7b8c6875dd72d8e4d6a295a583b9e9d5aaf376a6b5b3e8e"
    url = "https://github.com/JuliaBinaryWrappers/ZlibNG_jll.jl/releases/download/ZlibNG-v2.3.2+0/ZlibNG.v2.3.2.armv6l-linux-gnueabihf.tar.gz"
[[ZlibNG]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "af2a211c6a106f5e240a674cfef17c0c5d9d9233"
libc = "musl"
os = "linux"

    [[ZlibNG.download]]
    sha256 = "8aae2862d5988bc3c98f599baa8f6d7f5c3e2a088df79ca746e2d5d96a95445f"
    url = "https://github.com/JuliaBinaryWrappers/ZlibNG_jll.jl/releases/download/ZlibNG-v2.3.2+0/ZlibNG.v2.3.2.armv6l-linux-musleabihf.tar.gz"
[[ZlibNG]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "31f8a517328114d5bb941db3faa13ab45f7a2235"
libc = "glibc"
os = "linux"

    [[ZlibNG.download]]
    sha256 = "d9e7ac9b1f3bf99b8fe136a0c413fd90b2fac1a2c4538947f259eb783c6d1b61"
    url = "https://github.com/JuliaBinaryWrappers/ZlibNG_jll.jl/releases/download/ZlibNG-v2.3.2+0/ZlibNG.v2.3.2.armv7l-linux-gnueabihf.tar.gz"
[[ZlibNG]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "3da6add7818ecc17b5578f0e13c982676b0e030f"
libc = "musl"
os = "linux"

    [[ZlibNG.download]]
    sha256 = "5ae97c77a59917c816122a904523052849a795d021dd8dc567a1d5bb959da70e"
    url = "https://github.com/JuliaBinaryWrappers/ZlibNG_jll.jl/releases/download/ZlibNG-v2.3.2+0/ZlibNG.v2.3.2.armv7l-linux-musleabihf.tar.gz"
[[ZlibNG]]
arch = "i686"
git-tree-sha1 = "ec23b3645bc47a6b3d442bcb088c0c3eafe46ff0"
libc = "glibc"
os = "linux"

    [[ZlibNG.download]]
    sha256 = "8d97f2b05b0202f7ea0c761d9655de9ac6745c48abd6f788c27440a80162a73b"
    url = "https://github.com/JuliaBinaryWrappers/ZlibNG_jll.jl/releases/download/ZlibNG-v2.3.2+0/ZlibNG.v2.3.2.i686-linux-gnu.tar.gz"
[[ZlibNG]]
arch = "i686"
git-tree-sha1 = "d910cc0c10604a137983f3eca81c565930e3b229"
libc = "musl"
os = "linux"

    [[ZlibNG.download]]
    sha256 = "409a88ddfa7305f92d3624b008b6d78620fb142216ccf175e2b8bb7124fa480d"
    url = "https://github.com/JuliaBinaryWrappers/ZlibNG_jll.jl/releases/download/ZlibNG-v2.3.2+0/ZlibNG.v2.3.2.i686-linux-musl.tar.gz"
[[ZlibNG]]
arch = "i686"
git-tree-sha1 = "0963e3f98d0005d9be0f8bd3fc9f079886f90837"
os = "windows"

    [[ZlibNG.download]]
    sha256 = "b460512e0b429d70816c55cbcb4d251d8af105c4019c26cbd65554c95be989ad"
    url = "https://github.com/JuliaBinaryWrappers/ZlibNG_jll.jl/releases/download/ZlibNG-v2.3.2+0/ZlibNG.v2.3.2.i686-w64-mingw32.tar.gz"
[[ZlibNG]]
arch = "powerpc64le"
git-tree-sha1 = "90c25f0a8480837cd7d5e7b898bc253a0406dadf"
libc = "glibc"
os = "linux"

    [[ZlibNG.download]]
    sha256 = "310a3d4657d48ed18215e8fb62e2bddb6fd0aa6e476ec447ae8f22b8852b26e2"
    url = "https://github.com/JuliaBinaryWrappers/ZlibNG_jll.jl/releases/download/ZlibNG-v2.3.2+0/ZlibNG.v2.3.2.powerpc64le-linux-gnu.tar.gz"
[[ZlibNG]]
arch = "riscv64"
git-tree-sha1 = "c48c9827a33a15c7dd50e518294f29b8c0098f06"
libc = "glibc"
os = "linux"

    [[ZlibNG.download]]
    sha256 = "f7e573a0d4305f655518d4d03466c15978500a6a4ecacb82fe4f436e1aca0f92"
    url = "https://github.com/JuliaBinaryWrappers/ZlibNG_jll.jl/releases/download/ZlibNG-v2.3.2+0/ZlibNG.v2.3.2.riscv64-linux-gnu.tar.gz"
[[ZlibNG]]
arch = "x86_64"
git-tree-sha1 = "6a388ef0c64a93eacce87aea5b205f24cd5e963e"
os = "macos"

    [[ZlibNG.download]]
    sha256 = "2d8f8c594c60a07ba4494d25e195d7b656f414fec1e7f2704aac480b0188a5aa"
    url = "https://github.com/JuliaBinaryWrappers/ZlibNG_jll.jl/releases/download/ZlibNG-v2.3.2+0/ZlibNG.v2.3.2.x86_64-apple-darwin.tar.gz"
[[ZlibNG]]
arch = "x86_64"
git-tree-sha1 = "0c967de9591bd10fc8234ff450a7a0a54fdf115d"
libc = "glibc"
os = "linux"

    [[ZlibNG.download]]
    sha256 = "856fd305cf940472b97b379dcd3a766a2a48a4eed8c725970767e1a376d28358"
    url = "https://github.com/JuliaBinaryWrappers/ZlibNG_jll.jl/releases/download/ZlibNG-v2.3.2+0/ZlibNG.v2.3.2.x86_64-linux-gnu.tar.gz"
[[ZlibNG]]
arch = "x86_64"
git-tree-sha1 = "48a569226aaa3a7b39234a796d6930b653a8ee42"
libc = "musl"
os = "linux"

    [[ZlibNG.download]]
    sha256 = "20f44e1974b23f1cd6b20a7961397cb50c8a7f72ddc861912319284d44e4d5d3"
    url = "https://github.com/JuliaBinaryWrappers/ZlibNG_jll.jl/releases/download/ZlibNG-v2.3.2+0/ZlibNG.v2.3.2.x86_64-linux-musl.tar.gz"
[[ZlibNG]]
arch = "x86_64"
git-tree-sha1 = "c144062c1a13f9cacd585b65641b990021d9619a"
os = "freebsd"

    [[ZlibNG.download]]
    sha256 = "631ddaa0b6153d66a58e6c1b89306c55a27661bd94bfcbda4f290f68cb1f403d"
    url = "https://github.com/JuliaBinaryWrappers/ZlibNG_jll.jl/releases/download/ZlibNG-v2.3.2+0/ZlibNG.v2.3.2.x86_64-unknown-freebsd.tar.gz"
[[ZlibNG]]
arch = "x86_64"
git-tree-sha1 = "74a1deaa66ad2b666e0725abf04ff97efb695199"
os = "windows"

    [[ZlibNG.download]]
    sha256 = "e2cfa3b7407c4c162c7e07f3af60644855652e6dbec889d4f9b64852a1e3c6a6"
    url = "https://github.com/JuliaBinaryWrappers/ZlibNG_jll.jl/releases/download/ZlibNG-v2.3.2+0/ZlibNG.v2.3.2.x86_64-w64-mingw32.tar.gz"
