[[ZlibNG]]
arch = "aarch64"
git-tree-sha1 = "b4fec23f5d561006341f20140061aa0494beebec"
os = "macos"

    [[ZlibNG.download]]
    sha256 = "54159c747bdeb24768c5289ce92355ed0bc37272a6c113d061dacbc81230d5ca"
    url = "https://github.com/JuliaBinaryWrappers/ZlibNG_jll.jl/releases/download/ZlibNG-v2.2.2+0/ZlibNG.v2.2.2.aarch64-apple-darwin.tar.gz"
[[ZlibNG]]
arch = "aarch64"
git-tree-sha1 = "6a8c6cb2c0446d08d00aaca39d6fc6f4ca756752"
libc = "glibc"
os = "linux"

    [[ZlibNG.download]]
    sha256 = "6a0297f51e9e27e8033955981ebe88024987ca88845991bbb846730938246197"
    url = "https://github.com/JuliaBinaryWrappers/ZlibNG_jll.jl/releases/download/ZlibNG-v2.2.2+0/ZlibNG.v2.2.2.aarch64-linux-gnu.tar.gz"
[[ZlibNG]]
arch = "aarch64"
git-tree-sha1 = "59987f07f1d0008d37a2e5a5354cdc629d0394e5"
libc = "musl"
os = "linux"

    [[ZlibNG.download]]
    sha256 = "ef793b6a2621f93831d1f9130d28b58c32bf66a069f79fa2bc7a18d0c84fcfe0"
    url = "https://github.com/JuliaBinaryWrappers/ZlibNG_jll.jl/releases/download/ZlibNG-v2.2.2+0/ZlibNG.v2.2.2.aarch64-linux-musl.tar.gz"
[[ZlibNG]]
arch = "aarch64"
git-tree-sha1 = "e72efc9a698104af15f5252a49c227b72e0a4b8d"
os = "freebsd"

    [[ZlibNG.download]]
    sha256 = "fc1e289016739f6ba444add6a18f40d301dfa03a7b1fa09f9b1498ca8935a32f"
    url = "https://github.com/JuliaBinaryWrappers/ZlibNG_jll.jl/releases/download/ZlibNG-v2.2.2+0/ZlibNG.v2.2.2.aarch64-unknown-freebsd.tar.gz"
[[ZlibNG]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "0f798bc1de4c8d7af2b79706b280d67ddf98e15c"
libc = "glibc"
os = "linux"

    [[ZlibNG.download]]
    sha256 = "778dd46cb9201be167e65c355fa893e2c360317d42143d5320a0892830fd9b26"
    url = "https://github.com/JuliaBinaryWrappers/ZlibNG_jll.jl/releases/download/ZlibNG-v2.2.2+0/ZlibNG.v2.2.2.armv6l-linux-gnueabihf.tar.gz"
[[ZlibNG]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "179025142450a262f54056d4a2f60566e883bb33"
libc = "musl"
os = "linux"

    [[ZlibNG.download]]
    sha256 = "d49bcff1bcbc9f75bf6d1e413fe79f3a9c05fb16a002cce918064e2952d6a3cd"
    url = "https://github.com/JuliaBinaryWrappers/ZlibNG_jll.jl/releases/download/ZlibNG-v2.2.2+0/ZlibNG.v2.2.2.armv6l-linux-musleabihf.tar.gz"
[[ZlibNG]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "2518f3f73776bcd382b853f28095dbb573089793"
libc = "glibc"
os = "linux"

    [[ZlibNG.download]]
    sha256 = "f464f63c3cc55908ffff03088b9d253c2fda411da606070ccb89811b9a69ed8b"
    url = "https://github.com/JuliaBinaryWrappers/ZlibNG_jll.jl/releases/download/ZlibNG-v2.2.2+0/ZlibNG.v2.2.2.armv7l-linux-gnueabihf.tar.gz"
[[ZlibNG]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "23e1656ad289e1c04579041f2e0b74ee45830a59"
libc = "musl"
os = "linux"

    [[ZlibNG.download]]
    sha256 = "35a5ba5990fd4e8c7250c95c9b96878f3229b0feb29fa2cd0c70a3d0e510b87c"
    url = "https://github.com/JuliaBinaryWrappers/ZlibNG_jll.jl/releases/download/ZlibNG-v2.2.2+0/ZlibNG.v2.2.2.armv7l-linux-musleabihf.tar.gz"
[[ZlibNG]]
arch = "i686"
git-tree-sha1 = "31e64cbb83bc447d18379d72956a237d17961885"
libc = "glibc"
os = "linux"

    [[ZlibNG.download]]
    sha256 = "77242d875421766a19a5f9f9e1bb4bd1f31e66886bd4e1d22a210554dac253cb"
    url = "https://github.com/JuliaBinaryWrappers/ZlibNG_jll.jl/releases/download/ZlibNG-v2.2.2+0/ZlibNG.v2.2.2.i686-linux-gnu.tar.gz"
[[ZlibNG]]
arch = "i686"
git-tree-sha1 = "d3c755a0ef2c84fd3725e3b09446427643c8437e"
libc = "musl"
os = "linux"

    [[ZlibNG.download]]
    sha256 = "04e1d1f465cdf4561bdaf8a66a8e6468f75d2d20d30473655103bd04310ea4c8"
    url = "https://github.com/JuliaBinaryWrappers/ZlibNG_jll.jl/releases/download/ZlibNG-v2.2.2+0/ZlibNG.v2.2.2.i686-linux-musl.tar.gz"
[[ZlibNG]]
arch = "i686"
git-tree-sha1 = "28ca81dbb52ca0d18e5651d948b4fa446c24b158"
os = "windows"

    [[ZlibNG.download]]
    sha256 = "0c54e9c7f3f245ef8113cc12c0fee11dd86e2bad723daebe41db740d883b2d75"
    url = "https://github.com/JuliaBinaryWrappers/ZlibNG_jll.jl/releases/download/ZlibNG-v2.2.2+0/ZlibNG.v2.2.2.i686-w64-mingw32.tar.gz"
[[ZlibNG]]
arch = "powerpc64le"
git-tree-sha1 = "b6d67be0225c128e45a5827e7d62ddbc64f9008f"
libc = "glibc"
os = "linux"

    [[ZlibNG.download]]
    sha256 = "99ae6cd7c8adae0df427b97648377bfcddbc7f2f054cb097faaa17d34d826f84"
    url = "https://github.com/JuliaBinaryWrappers/ZlibNG_jll.jl/releases/download/ZlibNG-v2.2.2+0/ZlibNG.v2.2.2.powerpc64le-linux-gnu.tar.gz"
[[ZlibNG]]
arch = "x86_64"
git-tree-sha1 = "ec95506fef498dab99fa9a14845123d8544d0a33"
os = "macos"

    [[ZlibNG.download]]
    sha256 = "b5722c5d48f6a291c6eb4da08d94249d7143e832fe551713387e8a3cb08f4122"
    url = "https://github.com/JuliaBinaryWrappers/ZlibNG_jll.jl/releases/download/ZlibNG-v2.2.2+0/ZlibNG.v2.2.2.x86_64-apple-darwin.tar.gz"
[[ZlibNG]]
arch = "x86_64"
git-tree-sha1 = "20565f82e81e98193e0c324580f1443943209292"
libc = "glibc"
os = "linux"

    [[ZlibNG.download]]
    sha256 = "db27c8a29224fd35ca68fbfc0fc21d730471230f3d6c593b2a1cf1a7330acc00"
    url = "https://github.com/JuliaBinaryWrappers/ZlibNG_jll.jl/releases/download/ZlibNG-v2.2.2+0/ZlibNG.v2.2.2.x86_64-linux-gnu.tar.gz"
[[ZlibNG]]
arch = "x86_64"
git-tree-sha1 = "58881a837ba0e4be0d2e294d41693ff39ab3978f"
libc = "musl"
os = "linux"

    [[ZlibNG.download]]
    sha256 = "ff535e64282b59a5557e06e2b76d52be4b7eee6172e13f8fa15cb79c8c7ad340"
    url = "https://github.com/JuliaBinaryWrappers/ZlibNG_jll.jl/releases/download/ZlibNG-v2.2.2+0/ZlibNG.v2.2.2.x86_64-linux-musl.tar.gz"
[[ZlibNG]]
arch = "x86_64"
git-tree-sha1 = "7ef47aaac6bf67c962bdc02b929fc49d914222e0"
os = "freebsd"

    [[ZlibNG.download]]
    sha256 = "b84ffe4cead7182954914ac4f2dc10745be890bef31d6b6a5d8c2a9d5ea1b81a"
    url = "https://github.com/JuliaBinaryWrappers/ZlibNG_jll.jl/releases/download/ZlibNG-v2.2.2+0/ZlibNG.v2.2.2.x86_64-unknown-freebsd.tar.gz"
[[ZlibNG]]
arch = "x86_64"
git-tree-sha1 = "ad64b4b70dfb3d1b63f2287f4955517af5c15887"
os = "windows"

    [[ZlibNG.download]]
    sha256 = "faf8430d2fbf0ffde82efbb941298ba57c936eb0495476173f1d467044e6b743"
    url = "https://github.com/JuliaBinaryWrappers/ZlibNG_jll.jl/releases/download/ZlibNG-v2.2.2+0/ZlibNG.v2.2.2.x86_64-w64-mingw32.tar.gz"
