[[ZlibNG]]
arch = "aarch64"
git-tree-sha1 = "dc7f81367cc10c03cf1276a1f2dee447fa18219e"
os = "macos"

    [[ZlibNG.download]]
    sha256 = "54c179371e6df23fa795c2b9d3c89fbd78015e367e60110dc6a2f18c6ebd496a"
    url = "https://github.com/JuliaBinaryWrappers/ZlibNG_jll.jl/releases/download/ZlibNG-v2.2.5+0/ZlibNG.v2.2.5.aarch64-apple-darwin.tar.gz"
[[ZlibNG]]
arch = "aarch64"
git-tree-sha1 = "e342b843b952c946dcae4c535a45c0e10c20aa44"
libc = "glibc"
os = "linux"

    [[ZlibNG.download]]
    sha256 = "9c252641a819eabcb9e5f973a310a69e837f2d86e5b3691f47396e09d51422b7"
    url = "https://github.com/JuliaBinaryWrappers/ZlibNG_jll.jl/releases/download/ZlibNG-v2.2.5+0/ZlibNG.v2.2.5.aarch64-linux-gnu.tar.gz"
[[ZlibNG]]
arch = "aarch64"
git-tree-sha1 = "3dcc21218e7a1ff2dd8242a4ffbf18755443d423"
libc = "musl"
os = "linux"

    [[ZlibNG.download]]
    sha256 = "a22f40344acebc8fb1b4e0b0624b4a83d6b674137934e1928bcaed1a49719e4e"
    url = "https://github.com/JuliaBinaryWrappers/ZlibNG_jll.jl/releases/download/ZlibNG-v2.2.5+0/ZlibNG.v2.2.5.aarch64-linux-musl.tar.gz"
[[ZlibNG]]
arch = "aarch64"
git-tree-sha1 = "78225e06f7040497f0ab3d3c615800311fcc9410"
os = "freebsd"

    [[ZlibNG.download]]
    sha256 = "333ac0091ffe923a2df3ae3db7cfa4ee2a7e716392e93fcf8d9e9f290589c493"
    url = "https://github.com/JuliaBinaryWrappers/ZlibNG_jll.jl/releases/download/ZlibNG-v2.2.5+0/ZlibNG.v2.2.5.aarch64-unknown-freebsd.tar.gz"
[[ZlibNG]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "68e067ccbf729dd6273fdea9da4a494bf5cc19c5"
libc = "glibc"
os = "linux"

    [[ZlibNG.download]]
    sha256 = "65dee90b33e2774fb2f8aeb5d58c4c0b10a21914e061d24a71de11970559a9b9"
    url = "https://github.com/JuliaBinaryWrappers/ZlibNG_jll.jl/releases/download/ZlibNG-v2.2.5+0/ZlibNG.v2.2.5.armv6l-linux-gnueabihf.tar.gz"
[[ZlibNG]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "2552e091e54005f082fdd3a56675d846aba1951c"
libc = "musl"
os = "linux"

    [[ZlibNG.download]]
    sha256 = "8ce0f54cf7cecd775e220837dcf2c25250c2f2fbafd7d958363b74f88ba8f297"
    url = "https://github.com/JuliaBinaryWrappers/ZlibNG_jll.jl/releases/download/ZlibNG-v2.2.5+0/ZlibNG.v2.2.5.armv6l-linux-musleabihf.tar.gz"
[[ZlibNG]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "07c0bb4f785bb70e1a785d74b8a30de8811d46b9"
libc = "glibc"
os = "linux"

    [[ZlibNG.download]]
    sha256 = "ed79901a728a1832a8dc0b2c53a757314ad42b4cee02dc68c960581a99eb6a06"
    url = "https://github.com/JuliaBinaryWrappers/ZlibNG_jll.jl/releases/download/ZlibNG-v2.2.5+0/ZlibNG.v2.2.5.armv7l-linux-gnueabihf.tar.gz"
[[ZlibNG]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "51ea0b967e33685c9580173d4f38b03f72638525"
libc = "musl"
os = "linux"

    [[ZlibNG.download]]
    sha256 = "b1ab77c6a0410f8d09d135d541392dfe1f017705febd76f89cf76a2db9b1fd95"
    url = "https://github.com/JuliaBinaryWrappers/ZlibNG_jll.jl/releases/download/ZlibNG-v2.2.5+0/ZlibNG.v2.2.5.armv7l-linux-musleabihf.tar.gz"
[[ZlibNG]]
arch = "i686"
git-tree-sha1 = "8ff636efb9cde95dc08759fa4c5984d205d53a56"
libc = "glibc"
os = "linux"

    [[ZlibNG.download]]
    sha256 = "a2fa649d7a0c24320b07f04734380f181855f4784237135637554e373075dccf"
    url = "https://github.com/JuliaBinaryWrappers/ZlibNG_jll.jl/releases/download/ZlibNG-v2.2.5+0/ZlibNG.v2.2.5.i686-linux-gnu.tar.gz"
[[ZlibNG]]
arch = "i686"
git-tree-sha1 = "d5008dbb28ad5694316dc788c8d854aa0b9fd10f"
libc = "musl"
os = "linux"

    [[ZlibNG.download]]
    sha256 = "07d78fd1dae4551aec46a8d67c5b00981c5bd5f9230d3abec75167952e60222f"
    url = "https://github.com/JuliaBinaryWrappers/ZlibNG_jll.jl/releases/download/ZlibNG-v2.2.5+0/ZlibNG.v2.2.5.i686-linux-musl.tar.gz"
[[ZlibNG]]
arch = "i686"
git-tree-sha1 = "d78aabeb445347f475f89b68e9358c5de655b6c6"
os = "windows"

    [[ZlibNG.download]]
    sha256 = "29cb647a901b8d17bb13a19143dee7b7ecb003cfa9d0ed08726f3b8463a2055b"
    url = "https://github.com/JuliaBinaryWrappers/ZlibNG_jll.jl/releases/download/ZlibNG-v2.2.5+0/ZlibNG.v2.2.5.i686-w64-mingw32.tar.gz"
[[ZlibNG]]
arch = "powerpc64le"
git-tree-sha1 = "5747c581c81c88d5784c9a2ddd949caf4e82bb5b"
libc = "glibc"
os = "linux"

    [[ZlibNG.download]]
    sha256 = "7239602322315ce2da6dbfbcdc91108c7969b502476c0a02399d392980056fae"
    url = "https://github.com/JuliaBinaryWrappers/ZlibNG_jll.jl/releases/download/ZlibNG-v2.2.5+0/ZlibNG.v2.2.5.powerpc64le-linux-gnu.tar.gz"
[[ZlibNG]]
arch = "riscv64"
git-tree-sha1 = "19a6c636179b184f576446e3693a99a36ddd5fba"
libc = "glibc"
os = "linux"

    [[ZlibNG.download]]
    sha256 = "8c0303c81d910ecf4f6d4eccee131cc9d3f5922adf54a442cd10e56c9bc5ca46"
    url = "https://github.com/JuliaBinaryWrappers/ZlibNG_jll.jl/releases/download/ZlibNG-v2.2.5+0/ZlibNG.v2.2.5.riscv64-linux-gnu.tar.gz"
[[ZlibNG]]
arch = "x86_64"
git-tree-sha1 = "83f897ad48e571ecad9344fd0ff9cf9fe8550b08"
os = "macos"

    [[ZlibNG.download]]
    sha256 = "e2fbeae1d80c7a0537da3b9ea157bf5f97f5fdc133dbe4b6635f41ef08273e69"
    url = "https://github.com/JuliaBinaryWrappers/ZlibNG_jll.jl/releases/download/ZlibNG-v2.2.5+0/ZlibNG.v2.2.5.x86_64-apple-darwin.tar.gz"
[[ZlibNG]]
arch = "x86_64"
git-tree-sha1 = "a7c59c71e2b26b0a7f6fd7abe0ebe8d7fc95d789"
libc = "glibc"
os = "linux"

    [[ZlibNG.download]]
    sha256 = "47fdeb3ce9ae87977767a6e9ab5e41e13b518af97ad9e09a94f36b901bc332ed"
    url = "https://github.com/JuliaBinaryWrappers/ZlibNG_jll.jl/releases/download/ZlibNG-v2.2.5+0/ZlibNG.v2.2.5.x86_64-linux-gnu.tar.gz"
[[ZlibNG]]
arch = "x86_64"
git-tree-sha1 = "67dddf13e0a1af806be73031f7ecb2d3dd32930c"
libc = "musl"
os = "linux"

    [[ZlibNG.download]]
    sha256 = "b95c26e1778268370baa0a6ef84fbb75e1d9e7c64a241e98e0c74f8288cb4220"
    url = "https://github.com/JuliaBinaryWrappers/ZlibNG_jll.jl/releases/download/ZlibNG-v2.2.5+0/ZlibNG.v2.2.5.x86_64-linux-musl.tar.gz"
[[ZlibNG]]
arch = "x86_64"
git-tree-sha1 = "2d682083740240bb33bea31c0ea16b57d2ff03ce"
os = "freebsd"

    [[ZlibNG.download]]
    sha256 = "2acaf9fe6679d0e75ba484e15d4eb5300327ca07ecf61a8b633c4135a84bd298"
    url = "https://github.com/JuliaBinaryWrappers/ZlibNG_jll.jl/releases/download/ZlibNG-v2.2.5+0/ZlibNG.v2.2.5.x86_64-unknown-freebsd.tar.gz"
[[ZlibNG]]
arch = "x86_64"
git-tree-sha1 = "e9cbe4c9eca14163cc328d2c895dbc5efc9989ad"
os = "windows"

    [[ZlibNG.download]]
    sha256 = "dff384bdcaf174703ddc496046efab0357f8cb485462cf253ebda3387af92708"
    url = "https://github.com/JuliaBinaryWrappers/ZlibNG_jll.jl/releases/download/ZlibNG-v2.2.5+0/ZlibNG.v2.2.5.x86_64-w64-mingw32.tar.gz"
