[[ZlibNG]]
arch = "aarch64"
git-tree-sha1 = "f9c46eab9a879c07a6fa4577ba8c5c2056556765"
os = "macos"

    [[ZlibNG.download]]
    sha256 = "390bebd1398c6d037693c20efa7e66282b4dfbb8fbff28de646ba82fb1d022cb"
    url = "https://github.com/JuliaBinaryWrappers/ZlibNG_jll.jl/releases/download/ZlibNG-v2.3.3+1/ZlibNG.v2.3.3.aarch64-apple-darwin.tar.gz"
[[ZlibNG]]
arch = "aarch64"
git-tree-sha1 = "801f810a3a67828f881665a9308c8504cb267624"
libc = "glibc"
os = "linux"

    [[ZlibNG.download]]
    sha256 = "04b628854027604bb4602963b1df4eb82d4d2fc94704e76f6afd77c4b98541c5"
    url = "https://github.com/JuliaBinaryWrappers/ZlibNG_jll.jl/releases/download/ZlibNG-v2.3.3+1/ZlibNG.v2.3.3.aarch64-linux-gnu.tar.gz"
[[ZlibNG]]
arch = "aarch64"
git-tree-sha1 = "05eb2f4da338816ec694152f573d00bc78869cfc"
libc = "musl"
os = "linux"

    [[ZlibNG.download]]
    sha256 = "7d6e7be676c7a95f9ffe8c428c02a813e5a095d3b37e3458417fe5c328739f1b"
    url = "https://github.com/JuliaBinaryWrappers/ZlibNG_jll.jl/releases/download/ZlibNG-v2.3.3+1/ZlibNG.v2.3.3.aarch64-linux-musl.tar.gz"
[[ZlibNG]]
arch = "aarch64"
git-tree-sha1 = "eaef288673f6b0ae8c6acfc93951ec8969fb22ab"
os = "freebsd"

    [[ZlibNG.download]]
    sha256 = "2b953a95f7fbb799552fbea84b33f812a66f5a7966a1f781dd18800bd6983a9e"
    url = "https://github.com/JuliaBinaryWrappers/ZlibNG_jll.jl/releases/download/ZlibNG-v2.3.3+1/ZlibNG.v2.3.3.aarch64-unknown-freebsd.tar.gz"
[[ZlibNG]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "b268cabcdd8e3e93ed5365eb3ba1f80902c38970"
libc = "glibc"
os = "linux"

    [[ZlibNG.download]]
    sha256 = "4457833cbe6b9b08ee454b3e45c34de144c9b017e500150389523444a4cfa971"
    url = "https://github.com/JuliaBinaryWrappers/ZlibNG_jll.jl/releases/download/ZlibNG-v2.3.3+1/ZlibNG.v2.3.3.armv6l-linux-gnueabihf.tar.gz"
[[ZlibNG]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "e84edcd415191e1b5f5a428e7b84dd51ec97586a"
libc = "musl"
os = "linux"

    [[ZlibNG.download]]
    sha256 = "f7a85ecd8cce139cd5639f12be54813537320cbac7ad9fd6daf70b60c4c2464d"
    url = "https://github.com/JuliaBinaryWrappers/ZlibNG_jll.jl/releases/download/ZlibNG-v2.3.3+1/ZlibNG.v2.3.3.armv6l-linux-musleabihf.tar.gz"
[[ZlibNG]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "4696a71b12046f67a22d4022038a5ea1500cd674"
libc = "glibc"
os = "linux"

    [[ZlibNG.download]]
    sha256 = "ab3ba7186def17ef57dcd72f5fc159ee6d6cdd87ac21a977e4870e64d940ccc3"
    url = "https://github.com/JuliaBinaryWrappers/ZlibNG_jll.jl/releases/download/ZlibNG-v2.3.3+1/ZlibNG.v2.3.3.armv7l-linux-gnueabihf.tar.gz"
[[ZlibNG]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "9ab929ee0e2fe9314eab43529bfd0db9ec5ac045"
libc = "musl"
os = "linux"

    [[ZlibNG.download]]
    sha256 = "189950d586611b1225fa7aaebab60c16eec270c095c510a1bb1c2358ab9d4d0c"
    url = "https://github.com/JuliaBinaryWrappers/ZlibNG_jll.jl/releases/download/ZlibNG-v2.3.3+1/ZlibNG.v2.3.3.armv7l-linux-musleabihf.tar.gz"
[[ZlibNG]]
arch = "i686"
git-tree-sha1 = "9c597c3486dd4e507818da1392737559287b7676"
libc = "glibc"
os = "linux"

    [[ZlibNG.download]]
    sha256 = "be9ae26755e5f4b52e5186255395f62d98e62041e138c65b921bee3c28b08924"
    url = "https://github.com/JuliaBinaryWrappers/ZlibNG_jll.jl/releases/download/ZlibNG-v2.3.3+1/ZlibNG.v2.3.3.i686-linux-gnu.tar.gz"
[[ZlibNG]]
arch = "i686"
git-tree-sha1 = "22913a20035492b8184ec9faf883cb89585fe5f8"
libc = "musl"
os = "linux"

    [[ZlibNG.download]]
    sha256 = "648c670a0fc78c228bfd54de37f7df4f1f947418bb41ba37ffb35213a6a5bc50"
    url = "https://github.com/JuliaBinaryWrappers/ZlibNG_jll.jl/releases/download/ZlibNG-v2.3.3+1/ZlibNG.v2.3.3.i686-linux-musl.tar.gz"
[[ZlibNG]]
arch = "i686"
git-tree-sha1 = "ee94361bea829561b7ec80b4f462f64aaa078271"
os = "windows"

    [[ZlibNG.download]]
    sha256 = "68c1be58d5a694997c77d54ca599e88276245bf1c51ffa8a11a6f22f89718367"
    url = "https://github.com/JuliaBinaryWrappers/ZlibNG_jll.jl/releases/download/ZlibNG-v2.3.3+1/ZlibNG.v2.3.3.i686-w64-mingw32.tar.gz"
[[ZlibNG]]
arch = "powerpc64le"
git-tree-sha1 = "30eb1f808894ff8a3436bdf85e3ef1d7ba29ec65"
libc = "glibc"
os = "linux"

    [[ZlibNG.download]]
    sha256 = "a8a07506eac101c7e24e329f81d7e1f47e1a4e163f3a9770b8e035c10f1e814b"
    url = "https://github.com/JuliaBinaryWrappers/ZlibNG_jll.jl/releases/download/ZlibNG-v2.3.3+1/ZlibNG.v2.3.3.powerpc64le-linux-gnu.tar.gz"
[[ZlibNG]]
arch = "riscv64"
git-tree-sha1 = "52673c12bd1422a329d48004891e859e99fff596"
libc = "glibc"
os = "linux"

    [[ZlibNG.download]]
    sha256 = "16f908b7f872b9834794c1bf848e6e550a82cfe4ce4686afe52a3875bc4e653e"
    url = "https://github.com/JuliaBinaryWrappers/ZlibNG_jll.jl/releases/download/ZlibNG-v2.3.3+1/ZlibNG.v2.3.3.riscv64-linux-gnu.tar.gz"
[[ZlibNG]]
arch = "x86_64"
git-tree-sha1 = "1bae706cd7fda3510aa28f17e7aa60253d595816"
os = "macos"

    [[ZlibNG.download]]
    sha256 = "889015a25318aa0de772f28068fc2700e4656141d1c06c22aaa811c3c3e0b342"
    url = "https://github.com/JuliaBinaryWrappers/ZlibNG_jll.jl/releases/download/ZlibNG-v2.3.3+1/ZlibNG.v2.3.3.x86_64-apple-darwin.tar.gz"
[[ZlibNG]]
arch = "x86_64"
git-tree-sha1 = "cabdac7a39aa978bf42ff6bb2ace07ffb42cbd6b"
libc = "glibc"
os = "linux"

    [[ZlibNG.download]]
    sha256 = "71817ad29672d9a9550e8368d8c06fadc47dd71344d2e121b5510ee11bd3faed"
    url = "https://github.com/JuliaBinaryWrappers/ZlibNG_jll.jl/releases/download/ZlibNG-v2.3.3+1/ZlibNG.v2.3.3.x86_64-linux-gnu.tar.gz"
[[ZlibNG]]
arch = "x86_64"
git-tree-sha1 = "c2fc4e654ecea9e0437bd2ff5383f5bc03e4437a"
libc = "musl"
os = "linux"

    [[ZlibNG.download]]
    sha256 = "8c64242069b9a52faa32fdea70118507a54f12d598220225e52e85bfd145f0ca"
    url = "https://github.com/JuliaBinaryWrappers/ZlibNG_jll.jl/releases/download/ZlibNG-v2.3.3+1/ZlibNG.v2.3.3.x86_64-linux-musl.tar.gz"
[[ZlibNG]]
arch = "x86_64"
git-tree-sha1 = "6f19466b77b52baf8a535e92621bd296baf9141b"
os = "freebsd"

    [[ZlibNG.download]]
    sha256 = "55f1dfe42601c92e25955ec7634a15ccbfbea1d0f362003c464eb6c1d0f67280"
    url = "https://github.com/JuliaBinaryWrappers/ZlibNG_jll.jl/releases/download/ZlibNG-v2.3.3+1/ZlibNG.v2.3.3.x86_64-unknown-freebsd.tar.gz"
[[ZlibNG]]
arch = "x86_64"
git-tree-sha1 = "c68a3ab656fbb8d87a7575e9422e5be975c1f6ab"
os = "windows"

    [[ZlibNG.download]]
    sha256 = "807b65d84244af05178a3b87a3a63d832b1c014fff77d89eaea7cce1150b97e6"
    url = "https://github.com/JuliaBinaryWrappers/ZlibNG_jll.jl/releases/download/ZlibNG-v2.3.3+1/ZlibNG.v2.3.3.x86_64-w64-mingw32.tar.gz"
